#!/bin/sh
lock() {
    ~/.dotfiles/git/i3lock-fancy/lock -p -t ""
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        sudo pm-suspend && lock
        ;;
    hibernate)
        lock && pm-hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
